# fly.toml app configuration file generated for censorbib on 2026-06-16T12:27:53-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'censorbib'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
