<hr/>

<div class="left">
<a href="http://validator.w3.org/check?uri=referer">
<img src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Strict" height="31" width="88" />
</a>
<a href="http://jigsaw.w3.org/css-validator/check/referer">
<img style="border:0;width:88px;height:31px" src="http://jigsaw.w3.org/css-validator/images/vcss" alt="Valid CSS!" />
</a>
</div>

<div class="right">
Bibliography generated by <a href="https://github.com/NullHypothesis/bibliograpy"><tt>bibliograpy</tt></a>.
</div>

</body>
</html>
