server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Before Tigris, papers were self-hosted at censorbib.nymity.ch/pdf/.
    # To keep these legacy URLs working, we redirect them to Tigris.
    location = /pdf {
        return 301 https://censorbib-papers.t3.tigrisfiles.io/$is_args$args;
    }
    location ~ ^/pdf/(.*)$ {
        return 301 https://censorbib-papers.t3.tigrisfiles.io/$1$is_args$args;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
